global SV_VERBOSE
global NORM_VERBOSE
global CLUSTER_SAMPLE_VERBOSE
global SAMPLE_SIZE

SV_VERBOSE = True
EDA_VERBOSE = False
NORM_VERBOSE = True
CLUSTER_SAMPLE_VERBOSE = False
TSNE_VERBOSE = True
SAMPLE_SIZE = 5

